'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';

const S = {
  page: { minHeight: '100vh', background: 'var(--ivory)' },
  nav: { background: 'var(--burnham)', padding: '16px 32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  navTitle: { fontFamily: 'var(--font-ui)', fontSize: 11, letterSpacing: 3, color: 'var(--ivory)', textTransform: 'uppercase' },
  navBack: { fontFamily: 'var(--font-ui)', fontSize: 11, letterSpacing: 2, color: 'var(--celadon)', textTransform: 'uppercase', textDecoration: 'none' },
  body: { maxWidth: 760, margin: '0 auto', padding: '40px 24px' },
  section: { marginBottom: 40 },
  label: { fontFamily: 'var(--font-ui)', fontSize: 10, fontWeight: 700, letterSpacing: 2.5, textTransform: 'uppercase', color: '#6B6560', marginBottom: 12, display: 'block' },
  input: { width: '100%', padding: '11px 14px', border: '1.5px solid rgba(184,176,168,0.5)', borderRadius: 10, fontSize: 14, color: 'var(--jet)', background: '#fff', fontFamily: 'var(--font-body)', outline: 'none' },
  textarea: { width: '100%', padding: '11px 14px', border: '1.5px solid rgba(184,176,168,0.5)', borderRadius: 10, fontSize: 14, color: 'var(--jet)', background: '#fff', fontFamily: 'var(--font-body)', outline: 'none', resize: 'vertical', minHeight: 100 },
  colorRow: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8, background: '#fff', borderRadius: 10, padding: '10px 14px', border: '1.5px solid rgba(184,176,168,0.3)' },
  swatch: (hex) => ({ width: 32, height: 32, borderRadius: 8, background: hex, flexShrink: 0, border: '1px solid rgba(0,0,0,0.08)' }),
  saveBtn: { padding: '14px 40px', background: 'var(--burnham)', color: 'var(--ivory)', border: 'none', borderRadius: 40, fontSize: 13, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', fontFamily: 'var(--font-ui)', marginTop: 8 },
  savedMsg: { fontSize: 13, color: 'var(--burnham)', fontFamily: 'var(--font-ui)', fontWeight: 600, marginLeft: 16 },
  h1: { fontFamily: 'var(--font-serif)', fontSize: 36, fontWeight: 400, color: 'var(--burnham)', marginBottom: 6 },
  subtitle: { fontFamily: 'var(--font-body)', fontSize: 14, color: '#6B6560', marginBottom: 40 },
  divider: { border: 'none', borderTop: '1px solid rgba(184,176,168,0.4)', marginBottom: 40 },
  fieldRow: { display: 'flex', gap: 12, marginBottom: 16 },
  fieldHalf: { flex: 1 },
};

export default function BrandKitPage() {
  const [kit, setKit] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch('/api/brand')
      .then(r => r.json())
      .then(d => { if (d.error) setError(d.error); else setKit(d); })
      .catch(() => setError('Failed to load brand kit'));
  }, []);

  const save = async () => {
    setSaving(true); setSaved(false);
    const res = await fetch('/api/brand', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ colors: kit.colors, font_heading: kit.font_heading, font_body: kit.font_body, font_ui: kit.font_ui, guardrails: kit.guardrails }),
    });
    const d = await res.json();
    setSaving(false);
    if (d.error) setError(d.error);
    else { setKit(d); setSaved(true); setTimeout(() => setSaved(false), 3000); }
  };

  const updateColor = (i, field, val) => {
    const colors = [...kit.colors];
    colors[i] = { ...colors[i], [field]: val };
    setKit({ ...kit, colors });
  };

  if (error) return <div style={{ padding: 40, color: 'red' }}>{error}</div>;
  if (!kit) return <div style={{ padding: 40, fontFamily: 'var(--font-ui)', color: 'var(--burnham)' }}>Loading brand kit…</div>;

  return (
    <div style={S.page}>
      <nav style={S.nav}>
        <span style={S.navTitle}>The White Orchid — Brand Kit</span>
        <Link href="/" style={S.navBack}>← Back</Link>
      </nav>
      <div style={S.body}>
        <h1 style={S.h1}>Brand Kit</h1>
        <p style={S.subtitle}>The single source of truth for all visual output. Changes here apply to every post generated by school staff.</p>
        <hr style={S.divider} />

        {/* Colors */}
        <div style={S.section}>
          <span style={S.label}>Colour Palette</span>
          {kit.colors.map((c, i) => (
            <div key={i} style={S.colorRow}>
              <div style={S.swatch(c.hex)} />
              <input value={c.hex} onChange={e => updateColor(i, 'hex', e.target.value)}
                style={{ ...S.input, width: 110, fontFamily: 'monospace', fontSize: 13 }} />
              <input value={c.label} onChange={e => updateColor(i, 'label', e.target.value)}
                style={{ ...S.input, flex: 1 }} placeholder="Label" />
              <select value={c.role} onChange={e => updateColor(i, 'role', e.target.value)}
                style={{ ...S.input, width: 130 }}>
                <option value="primary">Primary</option>
                <option value="secondary">Secondary</option>
                <option value="accent">Accent</option>
                <option value="neutral">Neutral</option>
              </select>
            </div>
          ))}
        </div>

        <hr style={S.divider} />

        {/* Typography */}
        <div style={S.section}>
          <span style={S.label}>Typography</span>
          <div style={S.fieldRow}>
            <div style={S.fieldHalf}>
              <span style={{ ...S.label, fontSize: 9 }}>Heading / Serif</span>
              <input style={S.input} value={kit.font_heading} onChange={e => setKit({ ...kit, font_heading: e.target.value })} />
            </div>
            <div style={S.fieldHalf}>
              <span style={{ ...S.label, fontSize: 9 }}>Body</span>
              <input style={S.input} value={kit.font_body} onChange={e => setKit({ ...kit, font_body: e.target.value })} />
            </div>
            <div style={S.fieldHalf}>
              <span style={{ ...S.label, fontSize: 9 }}>UI / Labels</span>
              <input style={S.input} value={kit.font_ui} onChange={e => setKit({ ...kit, font_ui: e.target.value })} />
            </div>
          </div>
        </div>

        <hr style={S.divider} />

        {/* Guardrails */}
        <div style={S.section}>
          <span style={S.label}>Content Guardrails</span>
          <p style={{ fontSize: 13, color: '#6B6560', marginBottom: 12, fontFamily: 'var(--font-body)', lineHeight: 1.6 }}>
            Shown to staff before they export. Use this to communicate consent rules, tone-of-voice standards, and anything staff must check before posting.
          </p>
          <textarea style={S.textarea} value={kit.guardrails} onChange={e => setKit({ ...kit, guardrails: e.target.value })} />
        </div>

        <div style={{ display: 'flex', alignItems: 'center' }}>
          <button onClick={save} disabled={saving} style={{ ...S.saveBtn, opacity: saving ? 0.6 : 1 }}>
            {saving ? 'Saving…' : 'Save Brand Kit'}
          </button>
          {saved && <span style={S.savedMsg}>✓ Saved</span>}
        </div>
      </div>
    </div>
  );
}
