'use client';
import { useState, useEffect } from 'react';
import Nav from '@/components/Nav';

export default function BrandKitPage() {
  const [kit, setKit] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch('/api/brand').then(r => r.json()).then(d => { if (d.error) setError(d.error); else setKit(d); });
  }, []);

  const save = async () => {
    setSaving(true); setSaved(false);
    const res = await fetch('/api/brand', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ colors: kit.colors, font_heading: kit.font_heading, font_body: kit.font_body, font_ui: kit.font_ui, guardrails: kit.guardrails }),
    });
    const d = await res.json();
    setSaving(false);
    if (d.error) setError(d.error); else { setKit(d); setSaved(true); setTimeout(() => setSaved(false), 3000); }
  };

  const updateColor = (i, field, val) => {
    const colors = [...kit.colors];
    colors[i] = { ...colors[i], [field]: val };
    setKit({ ...kit, colors });
  };

  if (error) return <div style={{ padding: 40, color: 'var(--tw-tangerine)', fontFamily: 'var(--font-body)' }}>{error}</div>;
  if (!kit) return <div style={{ padding: 40, fontFamily: 'var(--font-syne)', color: 'var(--tw-burnham)', letterSpacing: '0.1em', textTransform: 'uppercase', fontSize: 12 }}>Loading…</div>;

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      <Nav section="brand kit" />
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '56px 32px' }}>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <div style={{ fontFamily: 'var(--font-syne)', fontSize: 11, fontWeight: 500, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--fg-subtle)', marginBottom: 12 }}>Admin</div>
          <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 400, color: 'var(--fg-strong)', lineHeight: 1.05, marginBottom: 12 }}>Brand kit</h1>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'var(--fg-muted)', lineHeight: 1.6, maxWidth: 480 }}>
            The single source of truth for all visual output. Changes here apply to every post generated by school staff.
          </p>
        </div>

        <hr style={{ border: 'none', borderTop: '1px solid var(--line)', marginBottom: 48 }} />

        {/* Colour palette */}
        <section style={{ marginBottom: 48 }}>
          <div style={{ fontFamily: 'var(--font-syne)', fontSize: 10, fontWeight: 700, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--fg-subtle)', marginBottom: 20 }}>Colour palette</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {kit.colors.map((c, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, background: 'var(--bg-raised)', borderRadius: 'var(--radius-md)', padding: '10px 16px', border: '1px solid var(--line)', boxShadow: 'var(--shadow-xs)' }}>
                <div style={{ width: 36, height: 36, borderRadius: 'var(--radius-sm)', background: c.hex, flexShrink: 0, border: '1px solid var(--line)' }} />
                <input value={c.hex} onChange={e => updateColor(i, 'hex', e.target.value)}
                  style={{ width: 100, padding: '8px 10px', border: '1px solid var(--line)', borderRadius: 'var(--radius-sm)', fontSize: 13, fontFamily: 'monospace', color: 'var(--fg-strong)', background: 'var(--bg)', outline: 'none' }} />
                <input value={c.label} onChange={e => updateColor(i, 'label', e.target.value)}
                  style={{ flex: 1, padding: '8px 12px', border: '1px solid var(--line)', borderRadius: 'var(--radius-sm)', fontSize: 14, fontFamily: 'var(--font-body)', color: 'var(--fg-strong)', background: 'var(--bg)', outline: 'none' }} />
                <select value={c.role} onChange={e => updateColor(i, 'role', e.target.value)}
                  style={{ padding: '8px 12px', border: '1px solid var(--line)', borderRadius: 'var(--radius-sm)', fontSize: 13, fontFamily: 'var(--font-body)', color: 'var(--fg-strong)', background: 'var(--bg)', outline: 'none', width: 120 }}>
                  <option value="primary">Primary</option>
                  <option value="secondary">Secondary</option>
                  <option value="accent">Accent</option>
                  <option value="neutral">Neutral</option>
                </select>
              </div>
            ))}
          </div>
        </section>

        <hr style={{ border: 'none', borderTop: '1px solid var(--line)', marginBottom: 48 }} />

        {/* Typography */}
        <section style={{ marginBottom: 48 }}>
          <div style={{ fontFamily: 'var(--font-syne)', fontSize: 10, fontWeight: 700, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--fg-subtle)', marginBottom: 20 }}>Typography</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
            {[['Heading / serif', 'font_heading', 'Romie'], ['Body', 'font_body', 'Fira Sans'], ['UI / labels', 'font_ui', 'Syne']].map(([label, key, placeholder]) => (
              <div key={key}>
                <div style={{ fontFamily: 'var(--font-syne)', fontSize: 9, fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--fg-subtle)', marginBottom: 8 }}>{label}</div>
                <input value={kit[key]} onChange={e => setKit({ ...kit, [key]: e.target.value })} placeholder={placeholder}
                  style={{ width: '100%', padding: '10px 12px', border: '1px solid var(--line)', borderRadius: 'var(--radius-sm)', fontSize: 14, fontFamily: 'var(--font-body)', color: 'var(--fg-strong)', background: 'var(--bg)', outline: 'none' }} />
              </div>
            ))}
          </div>
        </section>

        <hr style={{ border: 'none', borderTop: '1px solid var(--line)', marginBottom: 48 }} />

        {/* Guardrails */}
        <section style={{ marginBottom: 48 }}>
          <div style={{ fontFamily: 'var(--font-syne)', fontSize: 10, fontWeight: 700, letterSpacing: '0.18em', textTransform: 'uppercase', color: 'var(--fg-subtle)', marginBottom: 8 }}>Content guardrails</div>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--fg-muted)', lineHeight: 1.6, marginBottom: 16 }}>
            Shown to staff before export. Consent rules, tone-of-voice standards, anything to check before posting.
          </p>
          <textarea value={kit.guardrails} onChange={e => setKit({ ...kit, guardrails: e.target.value })}
            style={{ width: '100%', padding: '12px 16px', border: '1px solid var(--line)', borderRadius: 'var(--radius-md)', fontSize: 14, fontFamily: 'var(--font-body)', color: 'var(--fg-strong)', background: 'var(--bg)', outline: 'none', resize: 'vertical', minHeight: 120, lineHeight: 1.6 }} />
        </section>

        {/* Save */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <button onClick={save} disabled={saving}
            style={{ padding: '14px 40px', background: saving ? 'var(--tw-ash)' : 'var(--tw-burnham)', color: saving ? 'var(--fg-muted)' : '#fff', border: 'none', borderRadius: 'var(--radius-2xl)', fontFamily: 'var(--font-syne)', fontSize: 13, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', cursor: saving ? 'not-allowed' : 'pointer', transition: 'background 140ms' }}>
            {saving ? 'Saving…' : 'Save brand kit'}
          </button>
          {saved && <span style={{ fontFamily: 'var(--font-syne)', fontSize: 12, fontWeight: 600, color: 'var(--tw-celadon-deep)', letterSpacing: '0.06em' }}>✓ Saved</span>}
          {error && <span style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--tw-tangerine)' }}>{error}</span>}
        </div>
      </div>
    </div>
  );
}
