import { memo } from "react";

function Range({label,min,max,step,value,suffix,onChange,palette:B,fonts:F}){return <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:6}}><span style={{fontSize:12,fontFamily:F.subtitle,fontWeight:500,color:B.ash,minWidth:50}}>{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={event=>onChange(Number(event.target.value))} style={{flex:1,accentColor:B.burnham}}/><span style={{fontSize:12,fontFamily:F.body,color:B.ash,minWidth:40,textAlign:"right"}}>{suffix}</span></div>}
const swatch=(selected,color,B)=>({width:30,height:30,borderRadius:"50%",border:selected?`3px solid ${B.tangerine}`:`2px solid ${B.ash}66`,background:color,boxShadow:"0 0 0 2px #fff inset",cursor:"pointer"});

function OverlayInspectorPanel({layer,transform,isAccessory,roleLabel,isMediaHost,canUseAsMediaHost,onUseAsMediaHost,accessoryColors,accessorySizes,isMaster,isOverride,dimensionLabel,onMode,onStyle,onTransform,onReset,moreOpen,onToggleMore,lineArtMode="lineart",palette:B,fonts:F}){
  const mode=layer.mode||"frame";
  // (Line-art merge — client ruling 2026-08-18) ONE user-facing "Line art"
  // option. The internal renderer stays per-asset (`lineArtMode`: "outline"
  // for silhouette assets, "lineart" for line drawings) — the asset's bad
  // alternative is simply no longer offerable. Stored layers keep whichever
  // internal mode they carry, so existing designs render byte-identically.
  const isLineArt=mode==="outline"||mode==="lineart";
  const modeItems=[{id:"frame",label:"Frame",on:mode==="frame"},{id:"overlay",label:"Fill",on:mode==="overlay"},{id:lineArtMode,label:"Line Art",on:isLineArt}];
  const colorGroup=(title,keys,current,fallback,field)=><div style={{padding:"9px 11px",borderRadius:8,background:`${B.whiteSmoke}99`,border:`1px solid ${B.ash}33`,marginBottom:8}}><div style={{fontSize:10,color:B.ash,fontFamily:F.subtitle,fontWeight:700,letterSpacing:1,textTransform:"uppercase",marginBottom:6}}>{title}</div><div style={{display:"flex",flexWrap:"wrap",gap:7,marginBottom:9}}>{keys.map(key=><button key={key} aria-label={`${title} ${key}`} aria-pressed={(current||fallback)===key} title={key} onClick={()=>onStyle({[field]:key})} style={swatch((current||fallback)===key,B[key],B)}/>)}</div></div>;
  return <>
    {!isAccessory&&<><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8,padding:"9px 10px",marginBottom:10,borderRadius:8,background:`${B.celadonDeep}12`,border:`1px solid ${B.celadonDeep}30`}}><div><div style={{fontSize:9,color:B.ash,fontFamily:F.subtitle,fontWeight:700,letterSpacing:0.8,textTransform:"uppercase"}}>Purpose</div><div style={{fontSize:11,color:B.jet,fontFamily:F.subtitle,fontWeight:700,marginTop:2}}>{roleLabel||"Shape"}{isMediaHost?" · Active photo frame":""}</div></div>{canUseAsMediaHost&&!isMediaHost&&<button type="button" onClick={onUseAsMediaHost} style={{flexShrink:0,padding:"6px 9px",borderRadius:999,border:`1px solid ${B.burnham}`,background:"#fff",color:B.burnham,fontFamily:F.subtitle,fontSize:9,fontWeight:800,cursor:"pointer"}}>Use for photo</button>}{isMediaHost&&<span aria-label="This shape contains the photo" style={{fontSize:9,color:"#fff",background:B.burnham,borderRadius:999,padding:"5px 8px",fontFamily:F.subtitle,fontWeight:800}}>In use</span>}</div><div style={{fontSize:9,color:B.ash,fontFamily:F.subtitle,fontWeight:700,letterSpacing:0.8,textTransform:"uppercase",marginBottom:6}}>Appearance</div><div style={{display:"flex",gap:6,marginBottom:8}}>{modeItems.map(item=><button key={item.label} onClick={()=>onMode(item.id)} aria-pressed={item.on} style={{flex:1,padding:"6px 3px",borderRadius:7,border:`1.5px solid ${item.on?B.burnham:B.ash+"44"}`,background:item.on?B.burnham:"#fff",color:item.on?"#fff":B.jet,fontFamily:F.subtitle,fontSize:10,fontWeight:600,cursor:"pointer",whiteSpace:"nowrap"}}>{item.label}</button>)}</div>
      {mode==="overlay"&&<div style={{padding:"9px 11px",borderRadius:8,background:`${B.whiteSmoke}99`,border:`1px solid ${B.ash}33`,marginBottom:8}}><div style={{fontSize:10,color:B.ash,fontFamily:F.subtitle,fontWeight:700,letterSpacing:1,textTransform:"uppercase",marginBottom:6}}>Fill colour</div><div style={{display:"flex",flexWrap:"wrap",gap:7,marginBottom:9}}><button aria-label="Fill as-is" aria-pressed={!layer.fillColor} onClick={()=>onStyle({fillColor:""})} style={{...swatch(!layer.fillColor,"#fff",B),fontFamily:F.subtitle,fontSize:7,fontWeight:800,color:B.jet}}>AS-IS</button>{["tangerine","burnham","whiteSmoke","celadon","wisteria","dustyPink","jet"].map(key=><button key={key} aria-label={`Fill ${key}`} aria-pressed={layer.fillColor===key} onClick={()=>onStyle({fillColor:key})} style={swatch(layer.fillColor===key,B[key],B)}/>)}</div><Range label="Opacity" min={0} max={1} step={0.01} value={transform.opacity??1} suffix={`${Math.round((transform.opacity??1)*100)}%`} onChange={value=>onTransform({opacity:value})} palette={B} fonts={F}/></div>}
      {mode==="outline"&&<>{colorGroup("Line art colour",["tangerine","burnham","whiteSmoke","celadon","wisteria","jet"],layer.outlineColor,"tangerine","outlineColor")}<Range label="Weight" min={0.02} max={0.25} step={0.005} value={layer.outlineWidth??0.08} suffix={`${Math.round((layer.outlineWidth??0.08)*100)}%`} onChange={value=>onStyle({outlineWidth:value})} palette={B} fonts={F}/></>}
      {mode==="lineart"&&<>{colorGroup("Line art colour",["burnham","whiteSmoke","tangerine","celadon","wisteria","jet"],layer.lineArtColor,"burnham","lineArtColor")}<Range label="Ink sensitivity" min={0.45} max={0.9} step={0.01} value={layer.lineArtThreshold??0.72} suffix={`${Math.round((layer.lineArtThreshold??0.72)*100)}%`} onChange={value=>onStyle({lineArtThreshold:value})} palette={B} fonts={F}/><div style={{fontSize:10,color:B.ash,marginTop:5,fontFamily:F.body,lineHeight:1.45}}>Keeps dark linework, removes pale fill, then recolours the strokes.</div></>}
    </>}
    {isAccessory&&<><div style={{fontSize:10,color:B.ash,fontFamily:F.subtitle,fontWeight:700,letterSpacing:1,textTransform:"uppercase",marginBottom:6}}>Accessory colour</div><div style={{display:"flex",flexWrap:"wrap",gap:7,marginBottom:10}}>{accessoryColors.map(option=>{const selected=(transform.colorId||"auto")===option.id;return <button key={option.id} aria-label={`Accessory colour ${option.label}`} aria-pressed={selected} title={option.label} onClick={()=>onTransform({colorId:option.id})} style={{...swatch(selected,option.id==="auto"?B.whiteSmoke:B[option.id],B),width:34,height:34,fontFamily:F.subtitle,fontSize:option.id==="auto"?8:0,fontWeight:800,color:B.jet}}>{option.id==="auto"?"AUTO":""}</button>;})}</div><div style={{display:"flex",gap:6,marginBottom:9}}>{accessorySizes.map(item=><button key={item.id} aria-pressed={Math.abs((transform.scale||0)-item.scale)<0.015} onClick={()=>onTransform({scale:item.scale})} style={{flex:1,padding:"6px 5px",borderRadius:7,border:`1.5px solid ${Math.abs((transform.scale||0)-item.scale)<0.015?B.burnham:B.ash+"44"}`,background:Math.abs((transform.scale||0)-item.scale)<0.015?B.burnham:"#fff",color:Math.abs((transform.scale||0)-item.scale)<0.015?"#fff":B.jet,fontFamily:F.subtitle,fontSize:10,fontWeight:700,cursor:"pointer"}}>{item.label}</button>)}</div></>}
    <div style={{fontSize:10,color:B.ash,marginTop:4,fontFamily:F.body,lineHeight:1.45}}>{isAccessory&&(transform.colorId||"auto")==="auto"?"Auto selects an accessible brand colour. ":""}Drag on the preview to move, resize and rotate.</div>
    <button type="button" aria-expanded={moreOpen} onClick={onToggleMore} style={{marginTop:12,padding:0,border:"none",background:"transparent",fontFamily:F.subtitle,fontSize:10,fontWeight:700,letterSpacing:1,textTransform:"uppercase",color:B.burnham,cursor:"pointer"}}>More options {moreOpen?"▴":"▾"}</button>
    {moreOpen&&<div style={{marginTop:10,padding:"10px 12px",background:`${B.whiteSmoke}88`,borderRadius:8,border:`1px solid ${B.ash}33`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontSize:11,color:B.burnham,fontFamily:F.subtitle,fontWeight:700}}>{isMaster?"Default layout (Square)":isOverride?`Custom · ${dimensionLabel}`:"Auto from default"}</span><button onClick={onReset} style={{fontSize:10,color:B.tangerine,background:"none",border:"none",cursor:"pointer",fontFamily:F.body}}>{isMaster?"Reset":"Reset to auto"}</button></div><Range label="Size" min={isAccessory?0.04:0.05} max={isAccessory?0.8:1.6} step={0.01} value={transform.scale} suffix={`${Math.round(transform.scale*100)}%`} onChange={value=>onTransform({scale:value})} palette={B} fonts={F}/><Range label="Rotate" min={-180} max={180} step={1} value={transform.rotation||0} suffix={`${Math.round(transform.rotation||0)}°`} onChange={value=>onTransform({rotation:value})} palette={B} fonts={F}/><Range label="Opacity" min={0} max={1} step={0.01} value={transform.opacity??1} suffix={`${Math.round((transform.opacity??1)*100)}%`} onChange={value=>onTransform({opacity:value})} palette={B} fonts={F}/></div>}
  </>;
}

export default memo(OverlayInspectorPanel);
