import { memo } from "react";

function ShapeInspectorPanel({hasLayoutShapes,layoutSectionRef,layoutFlash,layoutPicker,layoutShape,onJumpLayout,layers,selectedId,onSelect,onDelete,selectedEditor,addOpen,onToggleAdd,addTray,palette:B,fonts:F}){
  return <>
    {hasLayoutShapes&&<div ref={layoutSectionRef} style={{marginBottom:16,borderRadius:10,transition:"box-shadow 0.3s",boxShadow:layoutFlash?`0 0 0 2px ${B.burnham}`:"none"}}><div style={{fontSize:10,color:B.burnham,fontFamily:F.subtitle,fontWeight:700,letterSpacing:1.4,textTransform:"uppercase",marginBottom:8}}>Layout shape</div>{layoutPicker}</div>}
    <div style={{fontSize:10,color:B.burnham,fontFamily:F.subtitle,fontWeight:700,letterSpacing:1.4,textTransform:"uppercase",marginBottom:8,paddingTop:hasLayoutShapes?12:0,borderTop:hasLayoutShapes?`1px solid ${B.ash}22`:"none"}}>Shapes on this design</div>
    {layoutShape&&<div style={{display:"flex",alignItems:"center",gap:8,padding:"6px 8px",borderRadius:9,border:`1.5px solid ${B.ash}33`,background:`${B.celadonDeep}0a`,marginBottom:6}}><button onClick={onJumpLayout} title={hasLayoutShapes?"This is the layout's own shape — tap to change it above":"This is the layout's own shape"} style={{flex:1,display:"flex",alignItems:"center",gap:8,background:"none",border:"none",cursor:hasLayoutShapes?"pointer":"default",padding:0,textAlign:"left"}}><span style={{width:30,height:30,borderRadius:7,background:`${B.celadonDeep}22`,display:"grid",placeItems:"center",flexShrink:0}}>{layoutShape.src?<img src={layoutShape.src} alt="" style={{maxWidth:22,maxHeight:22,objectFit:"contain"}}/>:<span aria-hidden="true" style={{fontSize:14,color:B.burnham}}>◆</span>}</span><span style={{display:"flex",flexDirection:"column",gap:2,minWidth:0}}><span style={{fontSize:11,fontFamily:F.subtitle,fontWeight:600,color:B.jet}}>{layoutShape.name||"Shape"}</span><span style={{fontSize:9,fontFamily:F.subtitle,fontWeight:700,letterSpacing:0.6,textTransform:"uppercase",color:B.celadonDeep}}>Layout shape</span></span></button></div>}
    {!layers.length?<div style={{fontSize:11,color:B.ash,fontFamily:F.body,lineHeight:1.5,marginBottom:10}}>{layoutShape?"No free shapes yet — the shape above is part of the layout. Add a free one below to drag, rotate and resize it on the preview.":"No free shapes yet. Add one below — then drag, rotate and resize it on the preview."}</div>:<div style={{display:"flex",flexDirection:"column",gap:6,marginBottom:10}}>{layers.map(layer=>{const selected=selectedId===layer.id;return <div key={layer.id} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 8px",borderRadius:9,border:`1.5px solid ${selected?B.burnham:B.ash+"33"}`,background:selected?`${B.burnham}0d`:"#fff"}}><button onClick={()=>onSelect(layer.id)} title="Edit this shape" style={{flex:1,display:"flex",alignItems:"center",gap:8,background:"none",border:"none",cursor:"pointer",padding:0,textAlign:"left"}}><span style={{width:30,height:30,borderRadius:7,background:`${B.celadonDeep}22`,display:"grid",placeItems:"center",flexShrink:0}}>{layer.src?<img src={layer.src} alt="" style={{maxWidth:22,maxHeight:22,objectFit:"contain"}}/>:<span aria-hidden="true" style={{fontSize:14,color:B.burnham}}>✦</span>}</span><span style={{display:"flex",flexDirection:"column",gap:2,minWidth:0}}><span style={{fontSize:11,fontFamily:F.subtitle,fontWeight:600,color:B.jet,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{layer.label}</span><span style={{fontSize:9,fontFamily:F.subtitle,fontWeight:700,letterSpacing:0.6,textTransform:"uppercase",color:B.ash}}>{layer.modeLabel}</span></span></button><button onClick={()=>onDelete(layer.id)} aria-label={`Delete ${layer.name||"shape"}`} title="Delete this shape (undoable)" style={{width:26,height:26,borderRadius:7,border:`1px solid ${B.ash}44`,background:"#fff",color:B.tangerine,cursor:"pointer",fontSize:14}}>×</button></div>;})}</div>}
    {selectedEditor&&<div style={{padding:"10px 11px",borderRadius:9,background:`${B.whiteSmoke}88`,border:`1px solid ${B.ash}2e`,marginBottom:10}}>{selectedEditor}</div>}
    <button onClick={onToggleAdd} aria-expanded={addOpen} style={{display:"inline-flex",alignItems:"center",gap:7,padding:"8px 14px",borderRadius:999,border:`1.5px solid ${B.burnham}`,background:addOpen?B.burnham:"#fff",color:addOpen?"#fff":B.burnham,fontFamily:F.subtitle,fontSize:11,fontWeight:700,cursor:"pointer"}}>＋ Add shape</button>{addOpen&&<div style={{marginTop:12}}>{addTray}</div>}
  </>;
}

export default memo(ShapeInspectorPanel);
